<?php
    class Lab extends Controller
	{
		function __contruct()
		{
			parent :: Controller();
		}
		
		function lab_index()
		{
			$data['title'] = "The Lab | Shutterbug Photo Mall";
			$data['header'] = "shared/general_header.php";
			$data['page'] = "lab/lab_view.php";
			
			$this->load->view('index.tpl.php', $data);
		}
		
		function products()
		{
			$data['title'] = "Products | The Lab | Shutterbug Photo Mall";
			$data['header'] = "shared/general_header.php";
			$data['page'] = "lab/product_view.php";
			
			$this->load->view('index.tpl.php', $data);
		}
		
		function lab_pro()
		{
			$data['title'] = "Pro Customers | The Lab | Shutterbug Photo Mall";
			$data['header'] = "shared/general_header.php";
			$data['page'] = "lab/pro_view.php";
			
			$this->load->view('index.tpl.php', $data);
		}
		
		function lab_catalog()
		{
			$data['title'] = "Pro Customers | The Lab | Shutterbug Photo Mall";
			$data['header'] = "shared/general_header.php";
			$data['page'] = "lab/catalog_view.php";
			
			$this->load->view('index.tpl.php', $data);
		}
		
		function catalog_process()
		{
			//This Loads Any Model Needed (nothing for now)
			$this->email->from('noreply@sbphotomall.com', 'Shutterbug Photo Mall');
			$this->email->to($this->input->post('email'));
			$this->email->subject('Thank You For Your Request '.$this->input->post('name'));
			
			$this->email->message('
			  <html>
			  <head>
			  </head>
			  <body>
			    <div>
				  <p>
				   Please don\'t respond to this email because it\'s being auto-generated by 
				   EventPhotoMarket.com.
				  </p>
				  <p>
				   Thank you for your request for our catalog. The Request will be sent through to
				   our people and you should recieve the catalog in a couple weeks. Thank you again
				   for your interest.
				  </p>
				  <p>
				   Sincerely, <br/><br/>
				   EventPhotoMarket.com
				  </p>
				</div>
			  </body>
			  </html>
			');
			
			$this->email->send();
			$this->email->clear();
			
			$this->email->to("info@eventphotomarket.com");
			$this->email->subject('Pro Catalog Registration From '.$this->input->post('name'));
			
			$this->email->message("
			  <html>
			  <head>
			  </head>
			  <body>
			    <div id='email_wrap'>
				  <p>
				   Please don't respond at this email because it's being auto-generated by 
				   EventPhotoMarket.com.
				  </p>
				  <p>
				   This is a Pro Catalog Request from ".$post['name'].". <br/>
				   Information is as follows:<br/>
				   <ul>
				     <li>Name: ".$post['name']."</li>
					 <li>Company: ".$post['company']."</li>
					 <li>Email: <a href='".$post['email']."'>".$post['email']."</a></li>
					 <li>Address: ".$post['address']."</li>
					 <li>City: ".$post['city']."</li>
					 <li>State: ".$post['state']."</li>
					 <li>Zip: ".$post['zip']."</li>
					 <li>Phone: ".$post['phone']."</li>
					 <li></li>
					 <h3>Answers to Questions:</h3>
					 <li>Are you digital? ".$post['digital']."</li>
					 <li># of kids: ".$post['q1']."</li>
					 <li># of Tournaments: ".$post['q2']."</li>
					 <li># of Employees: ".$post['q3']."</li>
					 <li>Length of Business: ".$post['q4']."</li>
					 <li>Photography Website: ".$post['q5']."</li>
					 <li>Associations: ".$post['q6']."</li>
					 <li>Kind's of Photography They Do: ".$post['q7']."</li>
					 <li>Current Client? ".$post['client']."</li>
				   </ul>		    
				  </p>
				  <p>
				   Sincerely, <br/><br/>
				   EventPhotoMarket.com
				  </p>
				</div>
			  </body>
			  </html>
			");
			$this->email->send();
			$this->email->clear();
			
			redirect('lab/catalog');
		}
	}
?>